services:
  - type: web
    name: zikos-karriere-chatbot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python3 app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        sync: false
